services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=main_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411'
